---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-site-content
  labels:
    app: www
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi