---
authentik:
    secret_key: "fjdskadjakfjdkasfjufdyagfhdgahfgdhagfdhgafdhgafhdgkafhdagfhdgsafdksga"
    error_reporting:
        enabled: false
    postgresql:
        password: "foobarpass"
    log_level: "info"


server:
    ingress:
        # Specify kubernetes ingress controller class name
        ingressClassName: nginx
        enabled: true
        hosts:
            - authentik.kevharv.com

postgresql:
    enabled: true
    auth:
        password: "foobarpass"
redis:
    enabled: true

global:
    additionalLabels:
        maintainer: kevin
    