---
all:
  children:
    nginx_rp:
      hosts:
        nginxrp.lab.kevharv.com:
          ansible_host: 192.168.1.10
          ansible_user: root  # DON'T DO THIS lol
          ansible_ssh_private_key_file: ~/.ssh/prox_lab
