---
all:
  hosts:
    awslbench001:
      ansible_host: awslbench001
      ansible_ssh_user: rocky
      ansible_ssh_private_key_file: ~/.ssh/aws_lab.pem
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"