---
- name: Install Common Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ common_packages }}"

- name: Set Message of the Day (/etc/motd)
  ansible.builtin.template:
    src: templates/motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
    backup: false

- name: Set Pre-Authentication Banner (/etc/banner)
  ansible.builtin.template:
    src: templates/banner.j2
    dest: /etc/banner
    owner: root
    group: root
    mode: 0644
    backup: false

- name: Append SSHD Configuration - Banner
  ansible.builtin.template:
    src: templates/sshd_banner.conf.j2
    dest: /etc/ssh/sshd_config.d/sshd_banner.conf
    owner: root
    group: root
    mode: 0600
    backup: false
  notify: restart-sshd

- name: Append SSHD Configuration - Disable Password Authentication
  ansible.builtin.template:
    src: templates/sshd_password_auth.conf.j2
    dest: /etc/ssh/sshd_config.d/sshd_password_auth.conf
    owner: root
    group: root
    mode: 0600
    backup: false
  notify: restart-sshd

- name: Install bashrc (system-level)
  ansible.builtin.template:
    src: templates/bashrc.j2
    dest: /etc/bash.bashrc
    owner: root
    group: root
    mode: 0644
    backup: true

- name: Install bashrc (running-user)
  ansible.builtin.template:
    src: templates/bashrc.j2
    dest: /home/{{ ansible_user }}/.bashrc
    backup: true
  become: false

- name: Install gitconfig
  ansible.builtin.template:
    src: templates/gitconfig.j2
    dest: /home/{{ ansible_user }}/.gitconfig
    backup: true
  become: false

- name: Remove Extra Directories
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/{{ directory }}
    state: absent
  become: false
  loop:
    - Music
    - Pictures
    - Public
    - Templates
    - Videos
  loop_control:
    loop_var: directory

- name: Install QEMU Guest Agent
  ansible.builtin.package:
    name: qemu-guest-agent
    state: present
  when: ansible_virtualization_role == 'guest'
