---
# OS Defaults
server_user: mcsvc
server_user_group: mcsvc_g
server_service_name: minecraft-server
server_install_path: /srv/{{ server_service_name }}
server_level_name: world
server_memory_allocation: 4G

# MC Installation
server_version: 1.21.4
server_eula: false       # By overriding this variable, you agree to https://aka.ms/MinecraftEULA.

# MC Configuration
server_port: 25565
server_rcon_port: 25575

# server.properties
# TODO - define remaining properties
server_properties_difficulty: normal
server_properties_enable_command_block: true
server_properties_motd: Minecraft Server deployed via Ansible!
server_properties_rcon_password: changeme!

