---
services:
    mc-springlus:
        container_name: mc-springlus
        image: itzg/minecraft-server
        tty: true
        stdin_open: true
        ports:
        - 25565:25565
        environment:
            EULA: "TRUE"
            MEMORY: "2G"
            TYPE: "AUTO_CURSEFORGE"
            CF_API_KEY: ${API_KEY}
            CF_SLUG: "custom"
            CF_MODPACK_MANIFEST: /manifests/manifest.json
        volumes:
        - mc-data:/data
        - ./manifest.json:/manifests/manifest.json:ro

volumes:
    mc-data: