---
- name: Virtual Workstation Post-Provisioning Configuration
  hosts: devwks1
  gather_facts: true
  become: true

  tasks:
    - name: Install Updates
      ansible.builtin.package:
        name: "*"
        state: latest

    - name: Apply Workstation Baseline
      ansible.builtin.include_role:
        name: workstation 
        