---
- name: Virtual Workstation Post-Provisioning Configuration
  hosts: kevwksubu
  gather_facts: true
  become: true

  tasks:
    - name: Install Updates
      ansible.builtin.package:
        name: "*"
        state: latest

    - name: Apply Workstation Baseline
      ansible.builtin.include_role:
        name: workstation

    - name: Create Caitlin's Account
      ansible.builtin.user:
        name: caitlin
        comment: Caitlin Harvey
        shell: /bin/bash
        home: /home/caitlin
        state: present

    # TODO
    # - create autoinstall.yml for automatic Ubuntu installation
    # - automatically stow dotfiles
    # - more apps
    #   - Steam
    #   - Blender
    #   - Unreal Engine 5 (Epic Games launcher)
        