---
authentik:
    secret_key: "fjdskadjakfjdkasfjufdyagfhdgahfgdhagfdhgafdhgafhdgkafhdagfhdgsafdksga"
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: false
    postgresql:
        password: "foobarpass"

server:
    ingress:
        # Specify kubernetes ingress controller class name
        ingressClassName: nginx
        enabled: true
        hosts:
            - authentik.kevharv.com

postgresql:
    enabled: true
    auth:
        password: "foobarpass"
redis:
    enabled: true
