---
- name: Remove Unecessary Filesystems
  community.general.modprobe:
    name: "{{ filesystem }}"
    state: absent
    persistent: absent
  loop_control:
    loop_var: filesystem
  loop:
    - cramfs
    - freevxfs
    - hfs
    - hfsplus
    - jffs2
    - overlay
    - squashfs
    - udf
    - firewire-core
    - usb-storage
    - ceph
    - cifs
    - exfat
    - ext
    # - fat   # IN USE by AWS instances
    - fscache
    # - fuse  # IN USE by AWS instances
    - gfs2
    - nfs_common
    - nfsd
    - smbfs_common
