---
- name: Remove Unecessary Filesystems
  community.general.modprobe:
    name: "{{ filesystem }}"
    state: absent
    persistent: absent
  loop_control:
    loop_var: filesystem
  loop:
    - cramfs
    - freevxfs
    - hfs
    - hfsplus
    - jffs2
    - overlay
    - squashfs
    - udf
    - firewire-core
    - usb-storage
    - ceph
    - cifs
    - exfat
    - ext
    - fscache
    - gfs2
    - nfs_common
    - nfsd
    - smbfs_common
    # - fat   # Required for vfat EFI partition
    # - fuse  # Required for S3/filesystem interop
  tags:
    - filesystem

- name: Ensure GPG Checking is Enabled
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: ^repo_gpgcheck
    line: repo_gpgcheck=1

- name: Find DNF Repositories with GPG Checking Disabled
  ansible.builtin.find:
    path: /etc/yum.repos.d
    patterns: "*.repo"
  register: discovered_repos

- name: Fix Repositories with GPG Checking Disabled
  ansible.builtin.replace:
    path: "{{ repo.path }}"
    regexp: ^repo_gpgcheck\s=s*0
    replace: repo_gpgcheck=1
  loop: "{{ discovered_repos.files }}"
  loop_control:
    loop_var: repo
    label: "{{ repo.path }}"

- name: Update All Packages to Latest
  ansible.builtin.package:
    name: "*"
    state: latest

- name: Enable SELinux
  ansible.posix.selinux:
    policy: targeted
    state: enforcing

- name: Ensure SELinux Enabled in Bootloader
  ansible.builtin.replace:
    path: /etc/default/grub
    regexp: "{{ item }}"
    replace: ""
  loop:
    - selinux=0
    - enforcing=0

- name: Remove SELinux Tools
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop:
    - mcstrans
    - setroubleshoot

- name: Set Bootloader Password
  ansible.builtin.copy:
    dest: /boot/grub2/user.cfg
    content: GRUB2_PASSWORD={{ cis_grub_password }}
    owner: root
    group: root
    mode: 'u-x,go-rwx'

- name: Disable Core Dump Backtrace
  ansible.builtin.lineinfile:
    path: /etc/systemd/coredump.conf
    regexp: "^ProcessSizeMax\\s*=\\s*.*[1-9]$"
    line: "ProcessSizeMax=0"
    mode: 'u-x,go-wx'
    owner: root
    group: root
    create: true

- name: Disable Core Dump Storage
  ansible.builtin.lineinfile:
    path: /etc/systemd/coredump.conf
    regexp: "^Storage\\s*=\\s*(?!none).*"
    line: "Storage=none"
    mode: 'u-x,go-wx'
    owner: root
    group: root
    create: true

- name: Ensure System Wide Crypography Policy Unset
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/sshd
    regexp: ^CRYPTO_POLICY\s*=
    state: absent

- name: Configure Cryptography Policies
  ansible.builtin.template:
    src: crypto/crypto.pmod.j2
    dest: /etc/crypto-policies/policies/modules/CRYPTO.pmod
    owner: root
    group: root
    mode: 'u-x,g-wx,o-rwx'

- name: Remove GDM
  ansible.builtin.package:
    name: gdm
    state: absent

- name: Set MOTD
  ansible.builtin.template:
    src: banners/motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'

- name: Set Issue
  ansible.builtin.template:
    src: banners/issue.j2
    dest: /etc/issue
    owner: root
    group: root
    mode: '0644'

- name: Set Net Issue
  ansible.builtin.template:
    src: banners/issue.net.j2
    dest: /etc/issue.net
    owner: root
    group: root
    mode: '0644'

- name: Configure SSH to Display Banner
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Banner'
    line: 'Banner /etc/issue.net'
    state: present
    validate: '/usr/sbin/sshd -t -f %s'
